- name: "virtualenv for {{ py_data.version }} | Check if virtualenv is already installed"
  become: true
  stat: path="{{ venv_home }}"
  register: already_installed
  ignore_errors: True
  when: should_install
  #- debug: msg="Install {{ should_install }}"


- name: " {{ py_data.version }} | Install virtualenv"
  become: true
  become_user: "{{ server.user.username }}"
  command: "{{ item }}"
  args:
    creates: "{{ venv_home }}"
  with_items:
    - "{{ py_data.bin }} -m venv {{ venv_home }}"
  when: should_install and not already_installed.stat.exists

- name: Recursively change ownership of a directory
  become: true
  file:
    path: "{{ venv_home }}"
    state: directory
    recurse: yes
    owner: "{{ server.user.username }}"
    #    group: "{{ server.user.group }},"  
