# Don't set gather_facts to no, apt need to get packages infornmation
---

- name: Install packages.
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages: "{{ apt_install }}"
    when: apt_install
  tags: apt
