# Don't set gather_facts to no, apt need to get packages infornmation
---

- name: Remove packages.
  apt: 
    name: "{{ packages }}"
    state: absent
  vars:
    packages: "{{ apt_remove }}"
    when: apt_remove
  tags: apt
